Add composer autoload
mailchimp/wordpress pull request #95
Opened 2024-12-26 20:54 UTC by MaxwellGarceau

### Description of the Change

Added autoloading to have an easy way to modularize new code and refactor existing code in the future.

**❗I modified the Github action workflow files to install composer dependencies in order to ensure autoload was being generated on every build. I wanted to flag this in case I missed a required build process update.**

Also, if there's a good place to add documentation for in progress pattern updates I'd be happy to add switching to autoload in new work and any refactors.

Closes #

### How to test the Change

### Changelog Entry

> Added - New feature
> Changed - Existing functionality
> Deprecated - Soon-to-be removed feature
> Removed - Feature
> Fixed - Bug fix
> Security - Vulnerability

### Credits

Props @username, @username2, ...

### Checklist:

- [ ] I agree to follow this project's [**Code of Conduct**](https://github.com/mailchimp/wordpress/blob/develop/CODE_OF_CONDUCT.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my change.
- [ ] All new and existing tests pass.

2025-01-02 16:14 UTC, dkotter requested changes
Overall this looks good but we'll need to do a few more things:

1. We have a GitHub Action that deploys plugin assets and readme changes. That will need to be updated to run `composer install` as well
2. We don't currently deploy the `vendor` directory so we'll need to update that or things won't work in the final release. We have both a `.distignore` and `.gitattributes` files that will need updated

2025-01-02 16:14 UTC, dkotter commented on mailchimp.php
> +	die( 'Composer autoload file not found. Run `composer install` to generate it.' );
Instead of using `die` here, I'd suggest instead we use a normal WordPress admin notice for a better user experience. Can see an example of that here: https://github.com/10up/restricted-site-access/blob/develop/restricted_site_access.php#L32-L58

2025-01-02 20:31 UTC, MaxwellGarceau commented on mailchimp.php
> +	die( 'Composer autoload file not found. Run `composer install` to generate it.' );
Good idea and thanks for the link! I just added the admin notice.

2025-01-02 20:48 UTC, MaxwellGarceau commented
> Overall this looks good but we'll need to do a few more things:
> 
> 1. We have a GitHub Action that deploys plugin assets and readme changes. That will need to be updated to run `composer install` as well
> 2. We don't currently deploy the `vendor` directory so we'll need to update that or things won't work in the final release. We have both a `.distignore` and `.gitattributes` files that will need updated

@dkotter I've made the requested changes.
1. Updated [.github/workflows/wordpress-plugin-asset-update.yml](https://github.com/mailchimp/wordpress/pull/95/files#diff-c3e586c1c6d72ed01af94b58e01c947574f715cca5273395f6d5710d604bcf49) with the `composer install` and autodump commands
2. Removed the vendor folder from distignore and gitattributes

2025-01-02 21:25 UTC, dkotter approved these changes

2025-01-18 21:34 UTC, qasumitbagthariya commented
### QA Update  ✅
---

- Run composer install to install dependencies and generate the autoload files. (Composer version 2.8.4) ✅

- Verify that the vendor/autoload.php file is generated. ✅

- Verify Functionality of Existing Features


<img width="598" alt="image" src="https://github.com/user-attachments/assets/0ac52aea-f28d-46bc-bbda-8a94b137f4a4" />

2025-01-18 21:34 UTC, qasumitbagthariya approved these changes

2025-01-27 22:26 UTC, jeffpaul approved these changes

2025-01-28 10:41 UTC, qasumitbagthariya commented
Regression / Smoke Test Report  ✅ 
-------

Tested with the `smoke-testing` branch, it works as expected, similar to the fix-specific branch.

**Testing Environment** 

<Details>

- WordPress: 6.7.1
- Theme: Storefront 4.6.0
- Theme: Twenty Twenty-Four 1.3
- WooCommerce - 9.5.1
- PHP: 8.0.30
- Web Server: Nginx 1.20.2
- Browser: Chrome 
- OS: macOS 15.2 
- Branch: smoke-testing

</Details>

2025-01-28 17:24 UTC, vikrampm1 commented
@dkotter got it. @iamdharmesh can you able to assist with the above as @MaxwellGarceau is not resourced on this project anymore?

2025-01-29 07:01 UTC, iamdharmesh commented
@dkotter E2E tests were failing because we are using the build release action from the develop branch, and it doesn't have the composer installation step. Due to an early return in the autoload file check, the plugin functionality was not getting enabled. I temporarily [pointed](https://github.com/mailchimp/wordpress/pull/95/commits/82116e0e55e2f429b2b6813d897fe0f3a6ef2eae) the build release action to this PR, and it started working as expected.

However, we recently enabled 2FA on the OSP account, and because of this, the connection tests and tests requiring connections are failing. I tried running the tests locally with a different account, and they worked well. So, it seems we are good to proceed here.

cc: @vikrampm1

2025-01-29 14:35 UTC, merged